In [3]:
import pandas as pd


In [5]:
import pandas as pd

In [6]:
import numpy as np

In [8]:
import numpy as np

numbers = np.array([10,20,30,40,50])

print(numbers)

[10 20 30 40 50]


In [9]:
numbers = np.array([10,20,30,40,50])
print(numbers)
print(numbers.shape)

[10 20 30 40 50]
(5,)


In [11]:
import numpy as np

arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [12]:
import numpy as np

arr3 = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(arr3)
print(arr3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [13]:
import numpy as np

a = np.array([5, 10, 15, 20])

print("Original Array:")
print(a)

print("\nAdd 10:")
print(a + 10)

print("\nMultiply by 2:")
print(a * 2)

print("\nSubtract 5:")
print(a - 5)

print("\nDivide by 5:")
print(a / 5)

Original Array:
[ 5 10 15 20]

Add 10:
[15 20 25 30]

Multiply by 2:
[10 20 30 40]

Subtract 5:
[ 0  5 10 15]

Divide by 5:
[1. 2. 3. 4.]


In [14]:
import numpy as np

x = np.array([10, 20, 30])

y = np.array([1, 2, 3])

print("Array X:", x)
print("Array Y:", y)

Array X: [10 20 30]
Array Y: [1 2 3]


In [15]:
print(x+y)

[11 22 33]


In [16]:
print(x-y)

[ 9 18 27]


In [17]:
print(x*y)

[10 40 90]


In [18]:
print(x/y)

[10. 10. 10.]


In [19]:
import numpy as np

A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

print("Matrix A")
print(A)

print("\nMatrix B")
print(B)

print("\nMatrix Multiplication")
print(A @ B)

Matrix A
[[1 2]
 [3 4]]

Matrix B
[[5 6]
 [7 8]]

Matrix Multiplication
[[19 22]
 [43 50]]


In [21]:
import pandas as pd

# Create sample student data
data = {
    "Name": ["Asha", "Rahul", "Priya", "Rohan", "Sneha"],
    "Math": [85, 78, 92, 74, 88],
    "Science": [90, 82, 95, 70, 91]
}

# Convert into DataFrame
df = pd.DataFrame(data)

# Save as CSV
df.to_csv("students.csv", index=False)

print("CSV file created successfully!")
print(df)

CSV file created successfully!
    Name  Math  Science
0   Asha    85       90
1  Rahul    78       82
2  Priya    92       95
3  Rohan    74       70
4  Sneha    88       91


In [22]:
df = pd.read_csv("students.csv")

print(df)

    Name  Math  Science
0   Asha    85       90
1  Rahul    78       82
2  Priya    92       95
3  Rohan    74       70
4  Sneha    88       91


In [24]:
import numpy as np

math_marks = df["Math"].to_numpy()

print("Math Marks:", math_marks)

print("Mean:", np.mean(math_marks))

Math Marks: [85 78 92 74 88]
Mean: 83.4


In [25]:
print("Standard Deviation:", np.std(math_marks))

Standard Deviation: 6.560487786742691


In [26]:
science_marks = df["Science"].to_numpy()

print(science_marks)

[90 82 95 70 91]


In [27]:
print(np.corrcoef(math_marks, science_marks))

[[1.         0.95843989]
 [0.95843989 1.        ]]


In [28]:
import numpy as np
import pandas as pd

# Create sample data
data = {
    "Name": ["Asha", "Rahul", "Priya", "Rohan", "Sneha"],
    "Math": [85, 78, 92, 74, 88],
    "Science": [90, 82, 95, 70, 91]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv("students.csv", index=False)

# Read CSV
df = pd.read_csv("students.csv")

print("Student Data:")
print(df)

# Convert columns to NumPy arrays
math_marks = df["Math"].to_numpy()
science_marks = df["Science"].to_numpy()

# Mean
print("\nMean of Math Marks:", np.mean(math_marks))

# Standard Deviation
print("Standard Deviation:", np.std(math_marks))

# Correlation
print("\nCorrelation Matrix:")
print(np.corrcoef(math_marks, science_marks))

Student Data:
    Name  Math  Science
0   Asha    85       90
1  Rahul    78       82
2  Priya    92       95
3  Rohan    74       70
4  Sneha    88       91

Mean of Math Marks: 83.4
Standard Deviation: 6.560487786742691

Correlation Matrix:
[[1.         0.95843989]
 [0.95843989 1.        ]]
